### PR TITLE
Kmercollection

### PR DESCRIPTION
**Pull request by Chrikomu**

### CODE REVIEW

**Comment by maasha** [comment]
Please document public methods.

**Comment by AndreasDahl** [comment]
This could use a few more unit tests. Is it otherwise ready to be merged?

**Comment by ahovgaard** [comment]
Why is the implementation all in the header file?

**Comment by ahovgaard** [comment]
Some unit tests of actual k-mer values could be good.
I've been looking a bit at it and I think it works alright for k != 8, but when k is 8 the k-mer values look very wrong to me. Are they not represented with 2 bits per nucleotide?

**Pull request merged**
